### ISSUE TITLE
switch changes state when clicked outside its outline

### ISSUE THREAD

**Issue by progamateur** [vlang/ui#100]
The switch changes state wherever you click in the window.

It seems that in "sw_click" function of swicht.v, mouse position test is missing.

To cope the issue, just modify the sw_click function as below :

fn sw_click(b mut Switch, e &MouseEvent, w &ui.Window) {
	if !b.point_inside(e.x, e.y) { return }	 //<===== mouse position test added
	if e.action == 0 {
		b.open = !b.open
		if b.onclick != 0 {
			b.onclick(w.user_ptr, b)
		}
	}
}

**Comment by memeone** [comment]
Hey! Can you make a PR for this? I currently don’t have access to a computer :)

**Comment by progamateur** [comment]
Hello @memeone, never done a PR. 
I'm just learning how to do it ! 
I hope I'm going to make it :)

**Comment by memeone** [comment]
Good learning opportunity 😄

**Comment by progamateur** [comment]
Done. (I hope all is OK !)

**Comment by medvednikov** [comment]
Congrats on your first contribution and thanks :)
