### ISSUE TITLE
v install ui failed

### ISSUE THREAD

**Issue by fxqy** [vlang/ui#102]
I wanted to install with v install ui but failed, I don't know why
![2174](https://user-images.githubusercontent.com/42601163/78455317-2f79ad80-76d0-11ea-8476-1f12ddc2099a.jpg)

**Comment by memeone** [comment]
Make sure you are on the latest version of v by running `v up` and also, v is quite unstable right now while we’re moving over to the new parser.

**Comment by gshields** [comment]
Repl is also down, with latest version
v install ui
V panic: V tool "E:\p-tools\v\cmd\tools\vpm.v" could not be compiled
["strings", "strconv.ftoa", "strings", "hash.wyhash", "strconv", "net.http", "os", "os.cmdline", "json", "vhelp", "math.bits", "os", "net.urllib", "net.http.chunked"]
E:\p-tools\v\vlib\net\http\http.v:230:0: error: unknown module `net_dot_urllib`
TODO: print_backtrace_skipping_top_frames_mingw(2)
print_backtrace_skipping_top_frames is not implemented on this platform for now...

v
For usage information, quit V REPL using `exit` and use `v help`
V 0.1.26 b056754.b056754
Use Ctrl-C or `exit` to exit
>>> 2400*3
error: bad top level statement name "println"

v version
V 0.1.26 b056754.b056754
windows 10

**Comment by fxqy** [comment]
Accessing ’github‘ on my network is too slow, I can only sync to ’gitee‘ and then clone to local

![20200405112222835](https://user-images.githubusercontent.com/42601163/78466085-d2154900-772f-11ea-80f8-344c4cdf25c1.jpg)
![20200405112258648](https://user-images.githubusercontent.com/42601163/78466088-d6d9fd00-772f-11ea-8e87-d1b2af2581c3.jpg)

**Comment by cctse** [comment]
latest version: V 0.1.26 50a8373.dbbfb04
```
❯ v install ui
cannot compile ‘/Users/cc/v/cmd/tools/vpm.v:
js.decode t=Mod
==================
^
/private/var/folders/20/5c9pj_4n21n_157qq7t10lv00000gp/T/v/vpm.tmp.c:13378:26: error: unexpected type name 'Mod': expected expression
                Mod mod = json__decode(Mod, s);
                                       ^
```

**Comment by medvednikov** [comment]
Fixed.
