### ISSUE TITLE
listbox.v:126:49: expected `=` or `:=`

### ISSUE THREAD

**Issue by mosfa** [vlang/ui#106]
/home/crt/.vmodules/ui/listbox.v:126:49: expected `=` or `:=`
  124| 
  125| // Returns the ID and the text of the selected item
  126| pub fn (lb &ListBox) selected() ?(string, string) {
                                                       ^
  127|     if !lb.is_selected() {
  128|         return error('Nothing is selected')

> **version: V 0.1.24 0d93eeb**

> **OS: Linux mint**

**Comment by leahlundqvist** [comment]
use V 0.1.25 to build V UI and examples:
https://github.com/vlang/v0.1.25

**Comment by mosfa** [comment]
> use V 0.1.25 to build V UI and examples:
> https://github.com/vlang/v0.1.25

**Comment by mosfa** [comment]
button.v:72:56: type `Window` is private
   70| }
   71| 
   72| fn btn_click(b mut Button, e &MouseEvent, window &Window) {
                                                              ^
   73| 	if b.point_inside(e.x, e.y) {
   74| 		if e.action == 1 {
first trouble gone, get second one 

> use V 0.1.25 to build V UI and examples:
> https://github.com/vlang/v0.1.25
