### ISSUE TITLE
Would you mind to rename this repo to `vui`?

### ISSUE THREAD

**Issue by changrui** [vlang/ui#11]
@medvednikov I think name this repo to `vui` and it's module named to `module vui`, do you think so?
another question: I can't close `v ui demo` window under `ubuntu 20.04`, but I can under `windows 10`, why?

**Comment by nedpals** [comment]
I think it makes more sense to just keep the current module name for the sake that its part of the modules created by the V team officially rather than developed by a person or by the community.
