### ISSUE TITLE
Updating module ui failed

### ISSUE THREAD

**Issue by Serkonda** [vlang/ui#115]
Running `v update ui` everytime throws an error:
```sh
Failed updating module "ui".
Failed command: git pull --depth=1
Failed details:
fatal: refusing to merge unrelated histories
```

I'm using the latest version of V with all new updates.

**Comment by Ulexus** [comment]
It appears the upstream history was messed up somewhere.  Just `git reset` your `ui` module, and it should be fine.  I just ran into this, as well.

**Comment by Serkonda** [comment]
Maybe it's because my knowledge of git commands is a bit limited but whatever I try, it won't work.
@Ulexus Have you further help?

**Comment by Ulexus** [comment]
Easiest is probably to just delete the module and re-add it:

```
v remove ui
v install ui
```

If that doesn't work, you can do the reset like I did:

```
cd $HOME/.vmodules/ui
git reset --hard origin/master
```

**Comment by Serkonda** [comment]
Until now I used your first workaround, but using `git pull --rebase` gets the latest changes without errors.
I'm waiting for new commits to test if this finally fixed the problem.

**Comment by Serkonda** [comment]
Should be fixed by https://github.com/vlang/v/pull/4869
