### ISSUE TITLE
How do I set a dependency on glfw?

### ISSUE THREAD

**Issue by Keyn1** [vlang/ui#134]
How do I set a dependency on glfw? The site only shows Windows: v setup-freetype. I did it. But the examples are not compiled.

the site says:
  Fedora:
  sudo dnf install **glfw** glfw-devel freetype-devel
  Windows:
  v setup-freetype

where glfw for windows?

if I do this:
 v install glfw
then I get an error

**Comment by spytheman** [comment]
The glfw library ( glfw3.lib and glfw3.dll) is already in V's main repository: https://github.com/vlang/v/tree/master/thirdparty/glfw .

Unlike freetype, it is much smaller, so there is no need to install it additionally with a special command.

**Comment by medvednikov** [comment]
glfw is no longer needed.
