### ISSUE TITLE
Examples broken by making UI's ft and gg not mutable

### ISSUE THREAD

**Issue by wwkeyboard** [vlang/ui#150]
It looks like a recent change made `ft` and `gg` public but not mutable in UI: https://github.com/vlang/ui/blob/master/ui.v#L21 this causes a bunch of errors in the example programs.

```
window.v:113:9: error: field `gg` of struct `&ui.UI` is immutable 
  111 |     ui_ctx.gg.window.onkeydown(window_key_down)
  112 |     ui_ctx.gg.window.onchar(window_char)
  113 |     ui_ctx.gg.window.onmousemove(window_mouse_move)
      |            ~~
  114 |     ui_ctx.gg.window.on_click(window_click)
  115 |     ui_ctx.gg.window.on_resize(window_resize)
```
If the best answer is to make those `pub mut` instead I'd be excited to sign the CLA and make the change.

**Comment by Serkonda** [comment]
Can be closed
