### ISSUE TITLE
Text misalignment on Linux

### ISSUE THREAD

**Issue by Serkonda** [vlang/ui#156]
**Version:** V master and latest UI
**OS:** Manjaro Linux

All text parts have a wrong alignment and are positioned slightly below the position they should have.

![Screenshot_20200609_120708](https://user-images.githubusercontent.com/40118727/84135067-c99c0000-aa49-11ea-8b10-83ebb16e1d80.png)

**Comment by BenStigsen** [comment]
**Version:** V master and latest UI
**OS:** Solus OS

Looks good on my end

![image](https://user-images.githubusercontent.com/24865450/85714573-d7f54780-b6ea-11ea-9a4f-b8a5a946fdfa.png)

**Comment by medvednikov** [comment]
This is going to be fixed soon after I finish the migration to the new graphics backend.

**Comment by Serkonda** [comment]
Is fixed
