### ISSUE TITLE
Group infinite auto expand

### ISSUE THREAD

**Issue by serkonda7** [vlang/ui#161]
**Version:** V master & latest UI
**OS:** Manjaro Linux

I found a bug where a groups size slowly increases into infinity. It seems that this only happens if the group is nested under a row and a column. 

**Reproduction code**
```v
import ui

struct App {
mut:
	window &ui.Window = 0
}

fn main() {
	mut app := &App{}
	app.window = ui.window({
		width: 1000
		height: 100
	}, [
		ui.column({}, [
			ui.row({
				height: 50
				spacing: 10
			}, [
				ui.group({
					title: 'test'
				}, [
					ui.button({})
				]),
			]),
		]),
	])
	ui.run(app.window)
}

```

**Comment by Serkonda** [comment]
The bug persists even with explicit height and width values.

**Comment by serkonda7** [comment]
**What fixes the problem:**
- remove the spacing
