### ISSUE TITLE
Memory usage increases over time

### ISSUE THREAD

**Issue by BenStigsen** [vlang/ui#165]
**Version**: Latest V and UI

I've had `users.v` running for ~20 minutes now, and the RAM usage has gone from around 25 MB to 101 MB.

**Comment by medvednikov** [comment]
I’m working on it right now.

**Comment by Serkonda** [comment]
Related to #60

**Comment by BenStigsen** [comment]
I hadn't seen that issue. I'll close this duplicate. See: #60
