### ISSUE TITLE
How to install manually without `v install ui`?

### ISSUE THREAD

**Issue by Zymlex** [vlang/ui#167]
How to install manually without `v install ui`?

Reason for question:
[issue 1](https://github.com/vlang/vpm/issues/9)
[issue 2](https://github.com/vlang/ui/issues/164)

**Comment by bashery** [comment]
in linux or mac os:
downlod it.
unzip
move it to ~/.vmodules
The result should be like this:
/home/\<you_name\>/.vmodules/ui

**Comment by Zymlex** [comment]
@bashery I work on Windows Server (with MSVC) and `ui` requires freetype:
`fatal error C1083: Cannot open include file: 'ft2build.h': No such file or directory`

**Comment by bashery** [comment]
did you try this command ? :
### v setup-freetype

**Comment by Zymlex** [comment]
@bashery Thanks!

At first I got an error:
```
Test.tmp.c
LINK : fatal error LNK1104: cannot open file 'glfw3.lib'
```
[this comment](https://github.com/vlang/v/issues/5042#issuecomment-634221561) is helped me and build without error,
but exe just doesn't start, as if it were empty.

**Comment by bashery** [comment]
Good!

**Comment by Zymlex** [comment]
Well, the install problem seems to be solved, so I'll close it.
