### ISSUE TITLE
Cannot use backspace in textbox on Solus OS 4.1

### ISSUE THREAD

**Issue by BenStigsen** [vlang/ui#171]
**OS:** Solus OS 4.1 Fortitude
**V Version:** 0.1.28

When I run the `users.v` example. I'm able to type in text, but when pressing backspace the cursor moves back but without deleting the character. 

Pressing DELETE seems to work as expected, by deleting the character that's in front of the current cursor position.

**Comment by Serkonda** [comment]
It works on Manjaro. Could you please try it again with updated V and UI.

**Comment by BenStigsen** [comment]
Yep, it seems to work with version 0.0.4
