### ISSUE TITLE
Resizable Fail

### ISSUE THREAD

**Issue by ElienayNathan** [vlang/ui#175]
I'm trying to make my window resizable, but something strange is happening.
![not-resizable1](https://user-images.githubusercontent.com/52963443/86519644-08d42b80-be13-11ea-8cf9-2d75fb1b37a3.PNG)
![not-resizable2](https://user-images.githubusercontent.com/52963443/86519645-0a9def00-be13-11ea-9373-9726bb888b55.PNG)

**Comment by Serkonda** [comment]
Duplicate of #92

**Comment by medvednikov** [comment]
Fixed.
