### ISSUE TITLE
Since coroutines are planned in V, I would like to ask you to use the state manager based on them, this will really be a breakthrough in this direction.

### ISSUE THREAD

**Issue by Omnuchka** [vlang/ui#2]
This is a very big advantage since _MobX_ or _Redux_ use asynchronous calls that can be discarded in  VUI in favor of such an innovative mechanism as **coroutines**.

**Comment by medvednikov** [comment]
Right now it's single threaded @Omnuchka, but I think coroutines can certainly be used in the future.
