### ISSUE TITLE
slider.v example - problem with mouse scroll

### ISSUE THREAD

**Issue by ManPython** [vlang/ui#202]
**V and UI versions:**  V 0.1.29 eabc2da
**OS:** W7

**What did you do?**
v run "C:\Users\user.vmodules\ui\examples\slider.v"

**What did you expect to see?**
1. Some window, but 
2. can't use mouse scroll, 
3. must click the control by mouse
4. clicked control have red frame and only arrow keys changing value - is this normal that mouse scroll not reacting? Or working this on LNX?
 
**What did you see instead?**
![v_slider](https://user-images.githubusercontent.com/25403861/90665816-da889f00-e24c-11ea-88ad-e51ab65fb74b.png)

Similar with other slider examples slider_textbox.v

**Comment by serkonda7** [comment]
Closing in favor of #207 (it's a little bit cleaner).
