### ISSUE TITLE
Problem with ui.textbox input

### ISSUE THREAD

**Issue by ManPython** [vlang/ui#203]
**V and UI versions:** V 0.1.29 eabc2da
**OS:** W7

**What did you do?**
1. run v change_title.v
2. run v slider_textbox.v

**What did you expect to see?**
1. on change_title.v if put some string value and after enter change the window title - no effct
2. on slider_textbox.v if put some int value and after enter change scroll position and some effect
 
**What did you see instead?**
Maybe working on LNX? Soo @serkonda7  .. next test for old and hated windows PC : )

**Comment by serkonda7** [comment]
Problems confirmed on Linux too.

**Comment by serkonda7** [comment]
The first problem you reported is not related to textboxes.

From a code comment:
> // TODO no set_title in Sokol

**Comment by serkonda7** [comment]
The first problem is resolved.

**Comment by kahsa** [comment]
both works on linux. maybe on windows.
