### ISSUE TITLE
Sliders can't be moved

### ISSUE THREAD

**Issue by ChildishGiant** [vlang/ui#207]
**V and UI versions:** V 0.1.29 ce4ee2b 
**OS:** Manjaro Linux x86_64

**What did you do?**
Copied the basic slider example

**What did you expect to see?**
Moveable sliders
 
**What did you see instead?**
Sliders can't be dragged or positioned
![Peek 2020-08-21 06-50](https://user-images.githubusercontent.com/13716824/90857890-fd19d580-e37c-11ea-8040-4a3db10c541b.gif)

**Comment by serkonda7** [comment]
Currently you can only use the arrow keys.

**Comment by kahsa** [comment]
already fixed.
