### ISSUE TITLE
button text is misplaced

### ISSUE THREAD

**Issue by fxqy** [vlang/ui#235]
**V version: 
    V 0.1.29 11f10fd.c5dc792
**UI version: 
    2020-09-27
**OS: 
    Microsoft Windows [版本 10.0.16299.125]

**What did you do?
    v run calculator.v 

The interface is not displayed properly and the button text is misplaced.

![image](https://user-images.githubusercontent.com/42601163/94353949-077c6d00-00a9-11eb-95b5-5f2b74db63ca.png)

**Comment by crthpl** [comment]
Mine is even worse:
<img width="257" alt="Screen Shot 2020-12-16 at 7 39 37 PM" src="https://user-images.githubusercontent.com/56052645/102441158-9927b680-3fd6-11eb-933d-38819eb70742.png">

**Comment by medvednikov** [comment]
@crthpl yeah this is a recent layout bug.

Will be fixed this week.

**Comment by kahsa** [comment]
This issue can be closed.
