### ISSUE TITLE
"error: unknown struct" of same directory?

### ISSUE THREAD

**Issue by kahsa** [vlang/ui#245]
**V version:0.1.29 6271798**
**UI version:**
**OS:ArchLinux** 

**What did you do?**
`v run moduletest.v`

mysample/moduletest.v is
```
module main

struct AB {
}

fn main() {
	ab := AB{}
	println(ab)
	cd := CD{}
	println(cd)
}
```
mysample/other.v

```
pub struct CD {
}

```

**What did you expect to see?**
```
AB{}
CD{}
 ```
**What did you see instead?**
```
moduletest.v:7:8: error: unknown struct: CD
    5 |     ab := AB{}
    6 |     println(ab)
    7 |     cd := CD{}
      |           ~~~~
    8 |     println(cd)
    9 | }
```

I'm new to v.
I don't understand well yet.
What am I wrong?

**Comment by kahsa** [comment]
Sorry! I made a misstake where to post!

**Comment by serkonda7** [comment]
You need to specify `module ...` for each file in the directory like this:
```v
module main

pub struct CD {
}
```

Then run with `v run .`

**Comment by serkonda7** [comment]
> Sorry! I made a misstake where to post!

This is not related to UI, so you should post such issues in the main repo next time https://github.com/vlang/v.
