### ISSUE TITLE
Missing Header files

### ISSUE THREAD

**Issue by mage1k99** [vlang/ui#250]
**V version: V 0.1.30 3afa606**
**UI version: 0.0.4**
**OS: Linux 5.4 KDE neon 5.20**
**Kernal version: 5.4.0-54-generic** 

**What did you do?**
I tried to Install V UI by installing V as per instructions. After the installation, I tried to run the examples that V UI came up with I encountered exceptions for missing include headers. Then I installed `libxi-dev` `libxcursor-dev` `libx11-dev`. I'm Having GCC compiler with build essentials installed

**What did you expect to see?**
 I expect to see a working v ui so i could start my project.

**What did you see instead?**
When I run users.v by `v run users.v` It shows
```
In file included from /tmp/v/calculator.11669164763337481806.tmp.c:785:
/home/mage1k99/Documents/compilers/v/thirdparty/sokol/sokol_app.h:1352:14: fatal error: GL/gl.h: No such file or directory
 1352 |     #include <GL/gl.h>
      |              ^~~~~~~~~
compilation terminated.
...
==================
(Use `v -cg` to print the entire error message)

builder error: 
==================
C error. This should never happen.

If you were not working with C interop, please raise an issue on GitHub:

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang

```

**Comment by serkonda7** [comment]
You are missing a package that's usually preinstalled on most systems.
I'm not fully sure but you might install `libmesa-dev` aswell.
