### ISSUE TITLE
Weird Spacing Issues

### ISSUE THREAD

**Issue by SteveGremory** [vlang/ui#280]
**V version:**  V 0.2.1 ca70d81
**UI version:** 0.0.4
**OS:** MacOS Big Sur

**What did you do?**

Tried One of the examples

**What did you expect to see?**

A fully functioning UI

**What did you see instead?**

The screenshot-
<img width="1680" alt="Screenshot 2021-01-19 at 7 58 04 PM" src="https://user-images.githubusercontent.com/38187217/105047935-fa88ec80-5a90-11eb-85fe-50370092c81e.png">

*By The Way, i'm VERY new to V, in-fact, i started today.

**Comment by kahsa** [comment]
Can you close this?

**Comment by SteveGremory** [comment]
Sure I can!
