### ISSUE TITLE
Fedora packages in README are wrong

### ISSUE THREAD

**Issue by Water261** [vlang/ui#284]
**V version:** 0.2.2 Commit: [69c3740](https://github.com/vlang/v/commit/69c37402d4074a23cceff5184a965b05ed079f83)
**UI version:** 0.0.4 Commit: [00b78c0](https://github.com/vlang/ui/commit/00b78c0fb419b669f14b16431195c72d388b9786)
**OS:** Linux x86_64 (Fedora 33)

**What did you do?** `v run users.v`

**What did you expect to see?** The users.v file to successfully launch. 

 
**What did you see instead?**
```bash
In file included from /tmp/v/users.6588665988430060396.tmp.c:824:
/home/myuser/Documents/V_Lang/v/thirdparty/sokol/sokol_app.h:1345:14: fatal error: X11/Xlib.h: No such file or directory
 1345 |     #include <X11/Xlib.h>
      |              ^~~~~~~~~~~~
compilation terminated.
```

The problem is the packages *libxi-dev libxcursor-dev* do not exist in Fedora 33 Repos, the packages that do work, although a little broken are *libXi-devel libXcursor-devel*, The Fedora section needs to be updated.

EDIT: Removed *libatomic* due to it being in the main V README
EDIT 2: Removed the photo due to it already being a known error

**Comment by changrui** [comment]
Yes!

**Comment by kahsa** [comment]
Can you close this?
