### ISSUE TITLE
can not install UI

### ISSUE THREAD

**Issue by sonwnja** [vlang/ui#303]
err:
![image](https://user-images.githubusercontent.com/15842446/108038689-1bcfff00-7076-11eb-8187-3a85fc90b0c4.png)

**Comment by alic110** [comment]
These problems occur a lot for someone in Windows

**Comment by alic110** [comment]
This has nothing to do with v-ui, you can mention it [here](https://github.com/vlang/v/issues/new/choose) or in [Discord (Recommended)](https://discord.gg/vlang)

**Comment by changrui** [comment]
It is fix. You can also install module `ui` by `cd v/vlib; git clone https://github.com/vlang/ui`.
