### ISSUE TITLE
Missing step for running V UI on ChromeOS Linux (Crostini)

### ISSUE THREAD

**Issue by jagtesh** [vlang/ui#316]
**V version:** V 0.2.2 8e69d36.57d1b5b
**UI version:**
**OS:** linux, N/A (VM) [Debian on ChromeOS/Crostini: Version 88.0.4324.153 (Official Build) (64-bit)]

**What did you do?**
`v run first.v` (a simple UI app that shows an empty window)

**What did you expect to see?**
The GUI window
 
**What did you see instead?**
```
==================
/usr/local/share/v/thirdparty/stdatomic/nix/atomic.h:117: warning: assignment from incompatible pointer type
tcc: error: library 'GL' not found
...
==================
(Use `v -cg` to print the entire error message)

builder error: 
==================
C error. This should never happen.

If you were not working with C interop, please raise an issue on GitHub:

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang
```

**Missing step to compile and run a V UI app on ChromeOS**
Install this package:
```apt install freeglut3-dev```
Source: https://stackoverflow.com/questions/50446867/importerror-library-glu-not-found/52886029

**Comment by jagtesh** [comment]
I am documenting this for the benefit of others who may run into this issue on ChromeOS. I can add a note in the documentation if someone can point me to the correct file.

**Comment by serkonda7** [comment]
@jagtesh in the UI readme we have a section about dependencies. 
Please feel free to create a PR there.

**Comment by jagtesh** [comment]
The PR is merged, so I will close this now.
