### ISSUE TITLE
v won't compile on macOS

### ISSUE THREAD

**Issue by stevekennedyuk** [vlang/ui#338]
**V version:**
0.2.2 3ea9868
**UI version:**
**OS:** 
Mac 11.2.3
**What did you do?**
v up

**What did you expect to see?**
self compile
 
**What did you see instead?**

Updating V...
recompiling vup.v failed:
vlib/time/time_darwin.c.v:70:16: error: cannot use `&u64` as `&time.time_t` in argument 1 to `C.localtime_r`
   68 |     C.gettimeofday(&tv, 0)
   69 |     loc_tm := C.tm{}
   70 |     C.localtime_r(&tv.tv_sec, &loc_tm)
      |                   ~~~~~~~~~~
   71 |     return convert_ctime(loc_tm, int(tv.tv_usec))
   72 | }

Current V version:
V 0.2.2 3ea9868, timestamp: 2021-04-05 11:04:31 +0300

**Comment by serkonda7** [comment]
Closing this, as it is not related to UI.
