### ISSUE TITLE
UI module in Windows make compile error

### ISSUE THREAD

**Issue by ali-ramezani** [vlang/ui#339]
V 0.2.2 8caabf0
**UI version:**
**OS:** Windows 10 (gcc 9.2 and msvc 16.9.2)

**What did you do?**
v up
v upgrade
v install ui
git clone https://github.com/vlang/ui.git
cd examples
v run users.v

I tried make -gcc and make -msvc and I got a similar error.

**What did you expect to see?** 
a compile program showing a window

 
**What did you see instead?**
ui_windows.c.v:10:18: error: cannot use `&u16` as `&char` in argument 2 to `C.MessageBox`
    8 | pub fn message_box(s string) {
    9 |     title := ''
   10 |     C.MessageBox(0, s.to_wide(), title.to_wide(), C.MB_OK)
      |                     ~~~~~~~~~~~
   11 | }

**Comment by tetorea** [comment]
got the same problem with v (V 0.2.2 40d32c7) compiled using tcc (windows 10).

The same error happens with the example file temperature.v

**Comment by blem14** [comment]
I've noticed this has been caused by [commit 4b2954a](https://github.com/vlang/ui/commit/4b2954a8efbb6ed4f042464e977fe889d86795eb) causing it to [fail CI](https://github.com/vlang/ui/runs/2292504045).

**Comment by serkonda7** [comment]
No, it's related to a change in V.

**Comment by williamclavier** [comment]
It appears that this problem can be solved with https://github.com/vlang/ui/pull/335/commits/22d7acec1e72ec3cff5b642dbbac004c3f2e094b
