### ISSUE TITLE
Glfw is still needed (on Ubuntu Mate 18.04 )

### ISSUE THREAD

**Issue by hubyhuby** [vlang/ui#341]
Glfw is still needed on Ubuntu (Mate) 18.04
Also it as been removed from 'readme dependencies' : https://github.com/vlang/ui/commit/ce81cedd961c26ce8593efc4c0309d672a4326fb

**V version:**
V built successfully!
Current V version:
V 0.2.2 d54becf, timestamp: 2021-04-10 10:46:43 +0300

**UI version:**
Installed today 10 April 2021
4b2954a8efbb6ed4f042464e977fe889d86795eb
**OS:** 
Unbuntu mat 18.04

**What did you do?**
 v run users.v

**What did you expect to see?**
The launching of the demo UI project
 
**What did you see instead?**

 v run users.v
==================
/home/yann/projects/v/v-src/v/thirdparty/stdatomic/nix/atomic.h:117: warning: assignment from incompatible pointer type
tcc: error: library 'GL' not found
...
==================
(Use `v -cg` to print the entire error message)

builder error: 
==================
C error. This should never happen.

If you were not working with C interop, this is a compiler bug, please raise an issue on GitHub:

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang

SOLUTION
After installing GLFW 3 it just worked.

![image](https://user-images.githubusercontent.com/26340942/114263802-f01f2480-99e7-11eb-8f39-a9105530e12a.png)

Thanks for this great Vlang  project !

**Comment by spytheman** [comment]
on Ubuntu/Debian, you need to run:
`sudo apt-get install libgl-dev libxi-dev libxcursor-dev` . Glfw3 is not needed (we use Sokol instead now), but may be it depends on these previous packages, so installing it, installed them too.
