### ISSUE TITLE
Unable to install on OSX.

### ISSUE THREAD

**Issue by micheg** [vlang/ui#342]
I was unable to install it on OSX 11.2.3.
This is what I get:

[local] michelangelo@air13:/tmp$ v up
Updating V...
Current V version:
V 0.2.2 ded3ce5, timestamp: 2021-04-17 12:30:45 +0300
[local] michelangelo@air13:/tmp$ v install ui
Errors while retrieving meta data for module ui:
Skipping module "ui", since https://vpm.vlang.io responded with 522 http status code. Please try again later.

**Comment by williamclavier** [comment]
Try again, the website was down the other day so the install wouldn't work for anyone. It's back up now so everything should work now.

**Comment by micheg** [comment]
yes perfect is gone.
I had caught the wrong time.

**Comment by Regan-Koopmans** [comment]
@micheg May we close this issue?

**Comment by micheg** [comment]
Sure, Thx.
