### ISSUE TITLE
installed error in kail linux

### ISSUE THREAD

**Issue by charlinone** [vlang/ui#354]
**V version:**  latest
**UI version:**  latest
**OS:** Kail linux 

**What did you do?**
sudo apt install libxi-dev libxcursor-dev mesa-common-dev  
./v install ui  

**What did you expect to see?**
no error info reported 
**What did you see instead?**

┌──(ling㉿kali)-[~/src/v]
└─$ ./v install ui                                           
failed    cmd: "/home/ling/src/v/v" "/home/ling/src/v/cmd/tools/vpm.v"
failed   code: 1
V panic: builder error: 'openssl/rand.h' not found

v hash: 94e7a55
/tmp/v/v2.exe.3443595821350599297.tmp.c:13303: at v_panic: Backtrace
/tmp/v/v2.exe.3443595821350599297.tmp.c:18336: by os__execute_or_panic
/tmp/v/v2.exe.3443595821350599297.tmp.c:26743: by v__util__launch_tool
/tmp/v/v2.exe.3443595821350599297.tmp.c:2374: by main__main
/tmp/v/v2.exe.3443595821350599297.tmp.c:3141: by main

**Comment by serkonda7** [comment]
You have to install openssl.
> V panic: builder error: 'openssl/rand.h' not found
