### ISSUE TITLE
add support qt

### ISSUE THREAD

**Issue by Mohammadwh** [vlang/ui#365]
hi 
how  i can use qt in vlang?

**Comment by kahsa** [comment]
Qt is/will not supported in vlib nor v-ui.

**Comment by serkonda7** [comment]
V UI will be an alternative to qt. 

If you really want to work with qt, you would have to write an wrapper for it (or wait for c2v to autogenerate one).
You may also look for existing qt-wrappers in awesome-v or on vpm.
