### ISSUE TITLE
Some examples don't work on windows os

### ISSUE THREAD

**Issue by fatihkizmaz** [vlang/ui#39]
Tried all ui examples. 
**All of them builds succesfully.** 
But some examples stops immediately with an error after program starts:

OS: Windows 10 x64

calculator (OK)
counter (OK)
**dropdown (STOPS WITH AN ERROR)**
slider (OK)
temperature (OK)
timer (OK)
**transitions (STOPS WITH AN ERROR)**
**users (STOPS WITH AN ERROR)**

Sample screenshot:
![image](https://user-images.githubusercontent.com/17065192/72661665-fa718f00-39ed-11ea-8875-26a3fa3c6587.png)

Also I needed to manually add freetype.dll to all example program's folders.
Otherwise program does not start caused by "freetype.dll" not found error.
(freetype directory exists at V's thirdparty directory.)

![image](https://user-images.githubusercontent.com/17065192/72661705-8be10100-39ee-11ea-9477-d133d4aa62d1.png)

**Comment by medvednikov** [comment]
Thanks for the detailed response.

**Comment by changrui** [comment]
You need to install `glfw` and `freetype` first as `README.MD`s of this repo and `https://github.com/vlang/v`.

**Comment by fatihkizmaz** [comment]
@changrui Yeah. freetype is installed as described in v/ui's readme. glfw is included for windows at v's thirdparty directory. 
Compilation of example programs completes succesfully. 
The problem occurs when trying to execute executables. I don't know what is the cause, but looks like memory related.

**Comment by adlesh** [comment]
@fatihkizmaz put glfw3.dll and freetype.dll in the folder w/ users.v

**Comment by adlesh** [comment]
By put i mean copy. I ran into this when i started messing w/ ui on windows.

**Comment by fatihkizmaz** [comment]
@adlesh Tried your suggestion. Not solved, same problem continues.

OS: Win 10 x64
V:  0.1.24 d92291d

**Comment by thecodrr** [comment]
@fatihkizmaz this will need to be debugged using gdb or windbg. The crash is due to runtime error, not compile time.

**Comment by SirWindfield** [comment]
I am getting compile time errors:

```
P:\projects\opensource\v\thirdparty\stb_image\stbi.obj already built.
P:\projects\opensource\v\thirdparty\glad\glad.obj already built.
V error: Microsoft (R) C/C++ Optimizing Compiler Version 19.24.28314 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

completionist.tmp.c
C:\Users\me\AppData\Local\Temp\v\completionist.tmp.c(11402): error C2440: 'type cast': cannot convert from 'ui__IWidgeter' to 'ui__IWidgeter'
```

I installed freetype into thirdparty and glfw is installed there as well. Any idea what might be wrong here? Running Windows 10.

**Comment by memeone** [comment]
@SirWindfield first off, long time no see! Iirc this is a bug in V that prevents V UI from working on windows atm. Should be fixed pretty soon.

**Comment by SirWindfield** [comment]
haha, I certainly didn't expect yo see you here :) Good to know, thanks!

**Comment by sveri** [comment]
> 
> 
> @SirWindfield first off, long time no see! Iirc this is a bug in V that prevents V UI from working on windows atm. Should be fixed pretty soon.

Hi, would be nice if there was a link to that issue so we can see here when it's fixed :-)

**Comment by memeone** [comment]
@sveri @SirWindfield should work if you compile v with mingw https://github.com/vlang/v/wiki/Installing-a-C-compiler-on-Windows

**Comment by serkonda7** [comment]
@fatihkizmaz is it still reproducible with latest V and UI?

**Comment by fatihkizmaz** [comment]
> @fatihkizmaz is it still reproducible with latest V and UI?

It works fine now.
