### ISSUE TITLE
Deprecation warnings

### ISSUE THREAD

**Issue by BenStigsen** [vlang/ui#406]
**V version: 0.2.4 ff95cf1.10f63b3**
**UI version: 23e1850**

The deprecation warnings are to be expected, due to a recent changes renaming `gg` drawing functions. I'm making this issue as a reminder for myself to fix it within the next couple of days, but also to explain why it's happening for people looking at existing issues.

**Comment by BenStigsen** [comment]
https://github.com/vlang/ui/pull/407

**Comment by kahsa** [comment]
can be closed
