### ISSUE TITLE
Unable to display text

### ISSUE THREAD

**Issue by QuentinWidlocher** [vlang/ui#412]
<details>
<summary>v doctor output</summary>

```
OS: linux, Ubuntu 20.04.3 LTS
Processor: 8 cpus, 64bit, little endian, Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
CC version: cc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

getwd: /mnt/809EB2A59EB292E0/Perso/v/test-ui-2
vmodules: /home/quentin/.vmodules
vroot: /mnt/809EB2A59EB292E0/Perso/v/v
vexe: /mnt/809EB2A59EB292E0/Perso/v/v/v
vexe mtime: 2022-01-13 12:54:47
is vroot writable: true
is vmodules writable: true
V full version: V 0.2.4 7882915.7fbd856

Git version: git version 2.25.1
Git vroot status: weekly.2021.46-534-g7fbd856b
.git/config present: true
thirdparty/tcc status: thirdparty-linux-amd64 3654d6a8
```

</details>

**What did you do?**

Executed `v run app.v` on this file :

<details>
<summary>app.v</summary>

```v
import ui

const (
	win_width  = 208
	win_height = 46
)

struct App {
mut:
	counter string     = '0'
	window  &ui.Window = 0
}

fn main() {
	mut app := &App{}

	app.window = ui.window(
		width: win_width
		height: win_height
		title: 'Counter'
		state: app
		children: [
			ui.row(
				spacing: 5
				margin: ui.Margin{5, 5, 5, 5}
				children: [
					ui.textbox(
						max_len: 20
						read_only: true
						is_numeric: true
						text: &app.counter
					),
					ui.button(
						width: 24
						height: 24
						text: 'Alt'
						onclick: btn_count_click
					),
				]
			),
		]
	)
	ui.run(app.window)
}

fn btn_count_click(mut app App, btn &ui.Button) {
	app.counter = (app.counter.int() + 1).str()
}
```

</details>

**What did you expect to see?**

A nice counter example
 
**What did you see instead?**

An ugly counter example without text, and the console logging `gg: draw_text(): font not initialized` repeatedly

**Comment by kahsa** [comment]
![Counter_001](https://user-images.githubusercontent.com/52106048/149625257-91323d24-912e-4d52-ba3c-20cb9da1037b.png)

No problem on my ArchLinux.

what is your result of `fc-match`?
or
```
import os.font
font.default()
```

**Comment by tzSharing** [comment]
> 

Why I set font_path, still can not display Chinese fonts normally.

![20220118022009](https://user-images.githubusercontent.com/90680948/149821439-aee4564e-b8e2-4bfd-9a4a-9ddd3beba09a.jpg)
![20220118021850](https://user-images.githubusercontent.com/90680948/149821498-1655cc14-02e0-4574-b62b-62c993cb9729.jpg)

**Comment by tzSharing** [comment]
> ![Counter_001](https://user-images.githubusercontent.com/52106048/149625257-91323d24-912e-4d52-ba3c-20cb9da1037b.png)
> 
> No problem on my ArchLinux.
> 
> what is your result of `fc-match -s`? or
> 
> ```
> import os.font
> font.default()
> ```
> 
> or you can set `font_path: '/path/to/your/favorite_font.ttf'` to `app.window`





**Why I set font_path, still can not display Chinese fonts normally？**

![20220118022009](https://user-images.githubusercontent.com/90680948/149821774-99f54086-015e-4c23-8f7a-15d6ac7145cf.jpg)
![20220118021850](https://user-images.githubusercontent.com/90680948/149821821-8c8d2e33-d7bd-4874-bb44-73ea5d1c4d2d.jpg)

**Comment by kahsa** [comment]
Is that `/fonts/font.ttf` an absolute path?
Seems a relative path to me.

**Comment by kahsa** [comment]
Currently, there are a lot of hardcoded places like this in `vlib`.
If you can figure out how to get the system's default fonts on Windows, please PR it.

**Comment by kahsa** [comment]
If you're using vscode, I'd recommend adding `v` and `.vmodules` folders to your workspace, like this.
That way you'll be able to find plenty of examples of `vlib` while learning with `Search: Find in Files`, `ctrl+shift+F`.
![範囲を選択_033](https://user-images.githubusercontent.com/52106048/149865614-3d72bbdb-994b-49e1-b80d-9145c3f3bd75.png)

**Comment by tzSharing** [comment]
> Is that `/fonts/font.ttf` an absolute path? Seems a relative path to me.
> 
> Or you can use https://modules.vlang.io/os.html#resource_abs_path like `fp := os.resource_abs_path(os.join_path('assets/fonts/', 'RobotoMono-Regular.ttf'))`
> 
> And I don't have Windows, so I could be wrong, but The way to specify the path is like this. https://github.com/vlang/v/blob/d8263171ff21809b6d5514dab481928ee2f3af22/vlib/os/font/font.v#L25

**I'm using Windows 10, I've tried many ways but all failed.But the absolute path of font_path printed out is correct.**
![20220118185944](https://user-images.githubusercontent.com/90680948/149926213-55b05256-d17a-4aa0-b19c-948b6e8cee81.jpg)

**Comment by kahsa** [comment]
@tzSharing
hmm.. try and see again change this path to your path and remove `app.font_path`.
https://github.com/vlang/v/blob/d8263171ff21809b6d5514dab481928ee2f3af22/vlib/os/font/font.v#L32

**Comment by tzSharing** [comment]
> @tzSharing hmm.. try and see again change this path to your path and remove `app.window.font_path`. https://github.com/vlang/v/blob/d8263171ff21809b6d5514dab481928ee2f3af22/vlib/os/font/font.v#L32
> 
> Are you living in China and discord is banned? https://discord.com/channels/592103645835821068/665558664949530644

Wow, with this method, I modified the `default()` source code in `v/vlib/os/font/font.v`, it was successfully repaired, I didn't even think of this method.  thanks.
In addition, regarding discord, my network is completely inaccessible, and GitHub can be accessed normally most of the time, but the speed is very slow.

I feel like this is a bug that needs to be fixed.

![20220118203851](https://user-images.githubusercontent.com/90680948/149943839-215b2fda-e612-41b2-9068-6f226391fb9b.jpg)
![20220118211227](https://user-images.githubusercontent.com/90680948/149943956-760f4073-5651-4aa2-8848-c3e23f3204ca.jpg)


![20220118203701](https://user-images.githubusercontent.com/90680948/149943907-c8da20f5-616e-452c-96d4-3432d0db3416.jpg)

**Comment by spytheman** [comment]
The `VUI_FONT` env variable, exists exactly for easy experimentation / overriding of the default font path.

**Comment by spytheman** [comment]
You can call `os.setenv('VUI_FONT', 'C:\\Windows\Fonts\\simfang.ttf', true)`, *before* your `font.default()` and/or gg calls, and then `font.default()` will return `'C:\\Windows\Fonts\\simfang.ttf'` without the need for patching the vlib source code.

**Comment by tzSharing** [comment]
> You can call `os.setenv('VUI_FONT', 'C:\\Windows\Fonts\\simfang.ttf', true)`, _before_ your `font.default()` and/or gg calls, and then `font.default()` will return `'C:\\Windows\Fonts\\simfang.ttf'` without the need for patching the vlib source code.

I just tried the method you said, and it works. I not only loaded the system fonts, but also successfully loaded the relative path fonts in the project.Thanks!
![20220122165344](https://user-images.githubusercontent.com/90680948/150632110-2ecb8088-e31d-4e21-8e93-c00f2ef1b642.jpg)
![20220122165040](https://user-images.githubusercontent.com/90680948/150632122-daf03e8a-3870-4294-a8cc-effec4f2aad9.jpg)
![20220122165130](https://user-images.githubusercontent.com/90680948/150632125-998bdf53-4240-42f8-940d-4c9cfe561ffd.jpg)
