### ISSUE TITLE
[Question]: Why isn't the code organized into a src directory?

### ISSUE THREAD

**Issue by Irtiza90** [vlang/ui#450]
i see a ton of .v files just lying around in the root directory for the repo
why is all of it not organized into one main directory called `src` or just `ui` like pretty much every Github repository

**Comment by spytheman** [comment]
Because it should be used by programs with just `import ui`.

**Comment by medvednikov** [comment]
I personally agree that it'd be cleaner in `src/`. V doesn't allow it yet, but it'd be nice to have.

**Comment by Irtiza90** [comment]
Hopefully it gets added soon.

**Comment by medvednikov** [comment]
Fixed.
