### ISSUE TITLE
general plan?

### ISSUE THREAD

**Issue by qzmfranklin** [vlang/ui#49]
What's the general plan of development and evolution of this project?

I'd use this information to gauge interests and plan for our team.

Any bluemap or directions or pointers would be desirable.

**Comment by medvednikov** [comment]
Here's roadmap to 0.1:

https://github.com/vlang/ui/issues/31

If you'd like to see something else implemented, suggestions are always welcome :)

The development of the framework is going to be fast, the goal is to have a stable usable toolkit asap.
