### ISSUE TITLE
failed to load /System/Library/Fonts/SFNSText.ttf

### ISSUE THREAD

**Issue by lydiandy** [vlang/ui#5]
os:mac10.15.2
when I run examples/users
v run users.v
got an error:
failed to load /System/Library/Fonts/SFNSText.ttf
gg create image "/var/folders/lk/k709921d2gl4jrh31mt8_ktm0000gn/T/check.png"
gg create image "/var/folders/lk/k709921d2gl4jrh31mt8_ktm0000gn/T/circle.png"
gg create image no such file "/var/folders/lk/k709921d2gl4jrh31mt8_ktm0000gn/T/circle.png"
gg create image "/var/folders/lk/k709921d2gl4jrh31mt8_ktm0000gn/T/selected_radio.png"
gg create image no such file "/var/folders/lk/k709921d2gl4jrh31mt8_ktm0000gn/T/selected_radio.png"
Terminated by signal 11 (SIGSEGV)

**Comment by medvednikov** [comment]
Fixed.
