### ISSUE TITLE
Many source files still have GPL header

### ISSUE THREAD

**Issue by rblath** [vlang/ui#524]
As the main LICENSE has been switched to MIT in commit 8fe7888, many source files still retain the GPL header at the top like this (src/menu.v):

```
// Copyright (c) 2020-2022 Alexander Medvednikov. All rights reserved.
// Use of this source code is governed by a GPL license
// that can be found in the LICENSE file.
```

I guess this will be fixed over time.

**Comment by spytheman** [comment]
Fixed in 56526d2 .
