### ISSUE TITLE
Doesn't work in linux

### ISSUE THREAD

**Issue by rkgarcia** [vlang/ui#53]
I can't run examples with the latest binary

./v run ~/.vmodules/ui/examples/users.v 
warning: vlib/clipboard/clipboard_linux.v:140:21: reference field `clipboard.Clipboard*.display` must be initialized
warning: vlib/clipboard/clipboard_linux.v:260:42: reference field `XSelectionRequestEvent*.display` must be initialized
warning: vlib/clipboard/clipboard_linux.v:364:19: `supported_targets` declared and not used
vlib/glfw/glfw.v:104:17: type `Window` is private
  102| }
  103| 
  104| pub fn (w &Window) destroy() {
                       ^
  105| 	C.glfwDestroyWindow(w.data)
  106| }

OS: Linux Elementary 0.4

**Comment by medvednikov** [comment]
Try `v up`

Install V from source if you are using a prebuilt package.

**Comment by rkgarcia** [comment]
I can't use with ```v up```but installing from sources finally works, thanks
