### ISSUE TITLE
V UI not run on macos 

### ISSUE THREAD

**Issue by yuchangfu** [vlang/ui#559]
**V version:0.4.3 be8e911**
**UI version:latest**
**OS:macos ventura** 

yuc@yuc examples % v run demo_label.v 
signal 11: segmentation fault
0   libsystem_platform.dylib            0x00007ff80cf835ed _sigtramp + 29
1   ???                                 0x0000000000000000 0x0 + 0
2   v                                   0x00000001041f96fb os__Process__spawn + 155
3   v                                   0x00000001041f9623 os__Process_wait + 35
4   v                                   0x000000010451e105 v__builder__Builder_run_compiled_executable_and_exit + 3701
5   v                                   0x000000010451b8dc v__builder__compile + 124
6   v                                   0x0000000104527379 main__rebuild + 121
7   v                                   0x0000000104526585 main__main + 2181
8   v                                   0x000000010452beb0 main + 64
9   dyld                                0x00007ff80cbfc41f start + 1903

**Comment by SamSandq** [comment]
As has been pointed out elsewhere, this is not a UI bug, but a V one.

Simply compile the program first and then run separately.
v demo_label.v
./demo_label

**Comment by spytheman** [comment]
`export VFLAGS="-use-os-system-to-run"` can also serve as a temporary workaround for the affected macos systems.

**Comment by JulienLecoq** [comment]
I think this issue can be closed, it works properly now.
