### ISSUE TITLE
Memory leaks in some examples

### ISSUE THREAD

**Issue by sereg1k** [vlang/ui#60]
**V version:** 0.1.24 [2897bac](https://github.com/vlang/v/commit/2897bac54977591e010cff8c9904debb479dc169)
**VUI:** 0.0.1 [1b17e4a](https://github.com/vlang/ui/commit/1b17e4a8a62f5ebd28feb913373476a0d3658225)
**OS:** Slackware 14.2 x86_64

**What did you do?**
1. `v -g run examples/calculator.v`
2. For some time, randomly move the cursor over the area of the calculator application.

**What did you expect to see?**
Memory consumption is not growing
 
**What did you see instead?**
Fast increase in memory consumption

**Addition:**
A memory leak is also in the examples/{counter.v, dropdown.v, temperature.v, timer.v, transitions.v, users.v}
No memory leak in examples/{slider.v, switch.v}

**Comment by thecodrr** [comment]
I can confirm.

**Comment by Serkonda** [comment]
I have no more memory leaks in any example.
