### ISSUE TITLE
failed to init the font

### ISSUE THREAD

**Issue by lydiandy** [vlang/ui#62]
os: mac
v version:V 0.1.24 7d79709
ui module:lastest version
when I run any examples,It will panic: failed to init the font.
and I found the code in ui.v may some problem.
line 152:
s := os.exec('fc-list') or { panic('failed to fetch system fonts') }
It requires fc-list command. but it is not a system command in mac.
I need install fontconfig by: brew install fontconfig.

and I follow the code to os_nix.v, line 208 may some problem:
'''
	res = res.trim_space()
	exit_code := vpclose(f)
	// if exit_code != 0 {
	// return error(res)
	// }
'''
when the exit_code is not 0,it will not raise an error

**Comment by medvednikov** [comment]
Yes, fc-list dep will be removed.

I thought it was a system tool :)

**Comment by fundon** [comment]
`brew install fontconfig`

**Comment by serkonda7** [comment]
With V 0.1.29 c01fd4a it still shows warnings (as in V 0.1.29 c01fd4a) but all the examples run.
