### ISSUE TITLE
running well but get many warnings under ubuntu 20.04 alpha.

### ISSUE THREAD

**Issue by changrui** [vlang/ui#8]
$ v run .
warning: /home/charles/vlang/vlib/clipboard/clipboard_linux.v:140:21: reference field `clipboard.Clipboard*.display` must be initialized
warning: /home/charles/vlang/vlib/clipboard/clipboard_linux.v:260:42: reference field `XSelectionRequestEvent*.display` must be initialized
warning: /home/charles/vlang/vlib/clipboard/clipboard_linux.v:364:19: `supported_targets` declared and not used
warning: /home/charles/vlang/vlib/ui/window.v:90:2: reference field `gg.Cfg.window_user_ptr` must be initialized
warning: /home/charles/vlang/vlib/ui/window.v:245:15: reference field `ui.TextBox*.parent` must be initialized
warning: /home/charles/vlang/vlib/ui/window.v:245:15: reference field `ui.TextBox*.ctx` must be initialized
warning: /home/charles/vlang/vlib/ui/window.v:246:14: reference field `ui.Button*.parent` must be initialized
warning: /home/charles/vlang/vlib/ui/window.v:246:14: reference field `ui.Button*.ctx` must be initialized
warning: /home/charles/vlang/vlib/ui/window.v:247:19: reference field `ui.ProgressBar*.parent` must be initialized
warning: /home/charles/vlang/vlib/ui/window.v:247:19: reference field `ui.ProgressBar*.ctx` must be initialized
warning: /home/charles/vlang/vlib/ui/window.v:248:16: reference field `ui.CheckBox*.parent` must be initialized
warning: /home/charles/vlang/vlib/ui/window.v:248:16: reference field `ui.CheckBox*.ctx` must be initialized
warning: /home/charles/vlang/vlib/ui/window.v:249:13: reference field `ui.Label*.parent` must be initialized
warning: /home/charles/vlang/vlib/ui/window.v:249:13: reference field `ui.Label*.ctx` must be initialized
warning: /home/charles/vlang/vlib/ui/window.v:250:13: reference field `ui.Radio*.parent` must be initialized
warning: /home/charles/vlang/vlib/ui/window.v:250:13: reference field `ui.Radio*.ctx` must be initialized
warning: /home/charles/vlang/vlib/ui/window.v:251:15: reference field `ui.Picture*.parent` must be initialized
warning: /home/charles/vlang/vlib/ui/window.v:251:15: reference field `ui.Picture*.ctx` must be initialized
warning: /home/charles/vlang/vlib/ui/window.v:306:1: the following imports were never used: 
 * gx
warning: ./users.v:50:2: reference field `Context*.first_name` must be initialized
warning: ./users.v:50:2: reference field `Context*.last_name` must be initialized
warning: ./users.v:50:2: reference field `Context*.age` must be initialized
warning: ./users.v:50:2: reference field `Context*.pbar` must be initialized
warning: ./users.v:50:2: reference field `Context*.window` must be initialized
warning: ./users.v:50:2: reference field `Context*.label` must be initialized
warning: ./users.v:187:1: `ctx` is declared as mutable, but it was never changed

**Comment by medvednikov** [comment]
Fixed.
