### ISSUE TITLE
Questions about license

### ISSUE THREAD

**Issue by adelarsq** [vlang/ui#85]
I have some questions about the license. On the `Readme.md` says:

> V UI is licensed under GPL3. A commercial license will be available. Open-source projects will have access to the commercial license for free. Every single feature will be open-sourced right away and available under both licenses. At some point in the future the library will be relicensed under MIT.

Will be a dual license? At some point will be necessary to pay a fee to use? Will be possible to use on closed commercial products at some point?

I want to use this library on my products, but this is a main blocker for me, since I only use open source tools and contribute when possible.

**Comment by adelarsq** [comment]
@joe-conigliaro @medvednikov Any ideas?

**Comment by medvednikov** [comment]
Sorry for the delay. V UI is open source, the license is GPL, to use in a non GPL project you would have to buy an affordable commercial license (around $100/year).

At some point it will be relicensed under MIT, similar to what happened to Xamarin.

**Comment by adelarsq** [comment]
No problem. Thanks @medvednikov

**Comment by adelarsq** [comment]
No problem. Thanks @medvednikov
So at this moment I can't use because the value is so high for me 😞
Anyway I will help when possible and use on my open source tools

**Comment by adelarsq** [comment]
This lib is now MIT! 🤗
