### ISSUE TITLE
Weird window artifacts on resize

### ISSUE THREAD

**Issue by Serkonda** [vlang/ui#92]
OS: Manjaro

Changing the size higher than default produces a lot of weird screen artifacts or just blank space in the new window space, as seen in the screenshots. Anything inside the default window size area or below works fine.

![Screenshot_20200304_170607](https://user-images.githubusercontent.com/40118727/75898863-f92fe080-5e3a-11ea-8fb9-ff747f811532.png)
![Screenshot_20200304_170640](https://user-images.githubusercontent.com/40118727/75898763-d1d91380-5e3a-11ea-84ad-241e1a837af4.png)

**Comment by madranet** [comment]
Same on OSX.

Although my artefacts aren't quite as psychedelic as yours!

![SS 2020-05-22 at 09 39 35](https://user-images.githubusercontent.com/669658/82648975-71bf6580-9c10-11ea-91aa-8f229f6664b7.png)

![SS 2020-05-22 at 09 40 41](https://user-images.githubusercontent.com/669658/82649006-7a17a080-9c10-11ea-8482-ef6651101874.png)

**Comment by medvednikov** [comment]
Will be fixed asap :)

**Comment by gorborukov** [comment]
Same artifacts Catalina 10.15.4
![Снимок экрана 2020-06-11 в 03 58 53](https://user-images.githubusercontent.com/2666067/84333295-02e28600-ab98-11ea-9097-80d06bc8a952.png)

**Comment by medvednikov** [comment]
Fixed.
