### ISSUE TITLE
HERESY! (Gui Design WSYIWYG)

### ISSUE THREAD

**Issue by andymans** [vlang/ui#95]
Just a suggestion:

The guys at XOJO have a very cool IDE for building apps - it's like the old VB6 Professional environment - but better. Obviously the language (a BASIC spin-off) is not terribly interesting - but from a 'What a nice, intuitive IDE for V/UI' perspective - you might want to grab a free download and play around with it. IMO it'd be a very big driver of adoption if the tooling was that good.

**Comment by dumblob** [comment]
Well, UI design tools help a whole lot in development of complex UIs.

But I'm quite certain, that the approach XOJO uses is actually highly inefficient. It's built around the ideas about mainstream GUIs in 90's (yes, XOJO dates back to 90's), though it supports modern platforms (Android, Raspi, ...).

The main deficiency of XOJO is it doesn't do **anything** to manage state. But state is what makes GUIs difficult to design and "develop". So XOJO actually completely misses the point.

Look at modern research on designing UIs and you might get totally blown away by their capabilities, but with fraction of effort needed e.g. with XOJO.

1. http://interstate.from.so/
2. https://sketch.systems/tutorials/iphone-lock-screen/ (click on the final version referenced in "*Sketches referenced in this tutorial*")
3. http://www.cs.cmu.edu/~shihpinc/gneiss.html
4. ... (e.g. https://github.com/pel-daniel/mind-bicycles )

**Comment by dumblob** [comment]
@andymans I didn't mean you should close this, but maybe rename the topic to a general discussion how to approach rapid development tooling around *V* UI :wink:.

**Comment by spytheman** [comment]
@andymans , @dumblob thanks for the links and references
