### ISSUE TITLE
Segmentation fault when loading users.exe on windows

### ISSUE THREAD

**Issue by shawnye** [vlang/ui#99]
OS: Windows 10  1809 (LSTC)

$ v -version
V 0.1.25 050ec5d

$ v users.v
warning: users.v:51:2: reference field `App*.window` must be initialized
warning: users.v:145:5: reference field `ui.PictureConfig.ref` must be initialized

$ ./users.exe
Trying to load font from C:\Windows\Fonts\arial.ttf
Segmentation fault

I find `C:\Windows\Fonts\arial.ttf` right there.

**Comment by serkonda7** [comment]
Could you please run `v up` and `v update ui` and test again.

**Comment by serkonda7** [comment]
Closed due to no respond. If you should encounter this bug again, please open a new issue.
